api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    path:     /homepage
    defaults: { _controller: AppBundle:Default:homepage }

appMain:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /