api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

api_login:
    path:     /api-login
    defaults: { _controller: ApiBundle:Default:login}

api_user:
    path:     /api-user
    defaults: { _controller: ApiBundle:Default:user}

api_mainPageEvent:
    path:     /api-mainPageEvent
    defaults: { _controller: ApiBundle:Default:mainPageEvent}

api_createEvent:
    path:     /api-createEvent
    defaults: { _controller: ApiBundle:Default:createEvent}

api_city:
    path:     /api-city
    defaults: { _controller: ApiBundle:Default:city}

api_category:
    path:     /api-category
    defaults: { _controller: ApiBundle:Default:category}

api_eventInfo:
    path:     /api-eventInfo
    defaults: { _controller: ApiBundle:Default:eventInfo}

api_goToEvent:
    path:     /api-goToEvent
    defaults: { _controller: ApiBundle:Default:goToEvent}

api_categoryPick:
    path:     /api-categoryPick
    defaults: { _controller: ApiBundle:Default:categoryPick}

api_register:
    path:     /api-register
    defaults: { _controller: ApiBundle:Default:register}

api_statusEvent:
    path:     /api-statusEvent
    defaults: { _controller: ApiBundle:Default:statusEvent}

api_thisWeek:
    path:     /api-thisWeek
    defaults: { _controller: ApiBundle:Default:thisWeek}

api_search:
    path:     /api-search
    defaults: { _controller: ApiBundle:Default:search}
